---
ID: "52e88e1e-2a2d-4c5a-ad29-419f538b5343"
Parent: "77cccc5c-c880-4d22-b428-d3d0f6da5d91"
Template: "77cccc5c-c880-4d22-b428-d3d0f6da5d91"
Path: /sitecore/templates/Project/ererenderingdering/Headless Tenant/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230304T105800Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "655c49cc-0483-4fbd-b2cf-0f27042b3da3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230304T105800Z
