---
ID: "db7888e7-d7aa-523c-90a3-0932c6b141e3"
Parent: "0e1d85cf-fd85-5fa2-8809-e0d6db2e2676"
Template: "0e1d85cf-fd85-5fa2-8809-e0d6db2e2676"
Path: "/sitecore/templates/Project/ererenderingdering/Styleguide-FieldUsage-Number/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230304T070423Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "688e54ab-f30c-4359-a86d-25447ff39e0c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230304T070423Z
