---
ID: "5478e3f7-c7ac-4f6f-914c-b8ad22d41ea7"
Parent: "8a03c117-c302-44ca-9a65-73beb655c706"
Template: "ab987746-78b0-4773-a8de-b295c493b7a4"
Path: /sitecore/content/Ererenderingdering/ErerenderingderingSXA/Settings/Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230304T105922Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6e934d3b-4575-4ab9-985b-b5abee5aa5ab"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230304T105922Z
