---
ID: "5816cb74-b8e6-529a-b21d-d625a97eeb0c"
Parent: "a32aa927-5b25-52dc-a939-c62a9fb91023"
Template: "a32aa927-5b25-52dc-a939-c62a9fb91023"
Path: "/sitecore/templates/Project/ererenderingdering/Styleguide-FieldUsage-ContentList/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230304T070421Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c76795da-9775-49e8-83db-2b2221ef8a9e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230304T070421Z
