---
ID: "7c1aaa2b-ef87-524a-af3c-640f67ffc87b"
Parent: "fb9d3467-591c-5a61-bd05-9f2c7994b85e"
Template: "fb9d3467-591c-5a61-bd05-9f2c7994b85e"
Path: "/sitecore/templates/Project/ererenderingdering/Styleguide-FieldUsage-Checkbox/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230304T070421Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a0a78d23-785d-409d-b9aa-5198fb4ae239"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230304T070421Z
